function createfigure(xdata1, ydata1, zdata1)
%CREATEFIGURE(xdata1, ydata1, zdata1)
%  XDATA1:  contour x
%  YDATA1:  contour y
%  ZDATA1:  contour z

%  Auto-generated by MATLAB on 15-Mar-2025 11:52:58

% Create figure
figure1 = figure('Name','Figure','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create contour
contour(xdata1,ydata1,zdata1);

% Create ylabel
ylabel('$\psi_\mathrm{y}$ [rad]','Interpreter','latex');

% Create xlabel
xlabel('$\psi_\mathrm{x}$ [rad]','Interpreter','latex');

box(axes1,'on');
grid(axes1,'on');
axis(axes1,'tight');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'BoxStyle','full','FontSize',15,'GridColor',[1 1 1],'Layer','top',...
    'TickLabelInterpreter','latex','XTick',...
    [0 0.785398163397448 1.5707963267949 2.35619449019234 3.14159265358979 3.92699081698724 4.71238898038469 5.49778714378214 6.28318530717959],...
    'XTickLabel',...
    {'0','$\pi/4$','$\pi/2$','$3\pi/4$','\pi','$5\pi/4$','3\pi/2','$7\pi/4$','2\pi'},...
    'YTick',...
    [0 0.785398163397448 1.5707963267949 2.35619449019234 3.14159265358979 3.92699081698724 4.71238898038469 5.49778714378214 6.28318530717959],...
    'YTickLabel',...
    {'0','$\pi/4$','$\pi/2$','$3\pi/4$','\pi','$5\pi/4$','3\pi/2','$7\pi/4$','2\pi'});
% Create colorbar
colorbar(axes1);

